In [5]:
import pandas as pd
import numpy as np
df=pd.read_csv('auto-mpg.csv',header=None)
print(df.head(5))
df.columns = [
    'mpg',
    'cylinders',
    'displacement',
    'horsepower',
    'weight',
    'acceleration',
    'model_year'
]

     0          1             2           3       4             5           6
0  mpg  cylinders  displacement  horsepower  weight  acceleration  model-year
1   18          8           307         130    3504            12          70
2   15          8           350         165    3693          11.5          70
3   18          8           318         150    3436            11          70
4   16          8           304         150    3433            12          70

In [14]:
import pandas as pd

mpg_to_kpl = 1.60934 / 3.78541

df['kpl'] = df['mpg'] * mpg_to_kpl

print(df.head(3))
print('\n')

df['kpl'] = df['kpl'].round(2)

print(df.head(3))

0   mpg cylinders displacement horsepower weight acceleration model-year  \
0  18.0         8          307        130   3504           12         70
1  15.0         8          350        165   3693         11.5         70
2  18.0         8          318        150   3436           11         70

0       kpl
0  7.652571
1  6.377143
2  7.652571


0   mpg cylinders displacement horsepower weight acceleration model-year   kpl
0  18.0         8          307        130   3504           12         70  7.65
1  15.0         8          350        165   3693         11.5         70  6.38
2  18.0         8          318        150   3436           11         70  7.65

In [7]:
df.head()

   mpg  cylinders  displacement  horsepower  weight  acceleration  model_year
0  mpg  cylinders  displacement  horsepower  weight  acceleration  model-year
1   18          8           307         130    3504            12          70
2   15          8           350         165    3693          11.5          70
3   18          8           318         150    3436            11          70
4   16          8           304         150    3433            12          70

In [8]:
# 1. Grab the values from the first row (index 0) to use as headers
df.columns = df.iloc[0]

# 2. Remove that first row from the data so it isn't duplicated
df = df.reindex(df.index.drop(0))

# 3. Optional: Reset the row index so it starts at 0 again
df = df.reset_index(drop=True)

In [13]:
df.head()

0   mpg cylinders displacement horsepower weight acceleration model-year
0  18.0         8          307        130   3504           12         70
1  15.0         8          350        165   3693         11.5         70
2  18.0         8          318        150   3436           11         70
3  16.0         8          304        150   3433           12         70
4  17.0         8          302        140   3449         10.5         70

In [12]:
df['mpg'] = pd.to_numeric(df['mpg'], errors='coerce')

In [15]:
print(df.dtypes)
print('\n')
print(df['horsepower'].unique())
print('\n')

0
mpg             float64
cylinders        object
displacement     object
horsepower       object
weight           object
acceleration     object
model-year       object
kpl             float64
dtype: object


['130' '165' '150' '140' '198' '220' '215' '225' '190' '170' '160' '95'
 '97' '85' '88' '46' '87' '90' '113' '200' '210' '193' nan '100' '105'
 '175' '153' '180' '110' '72' '86' '70' '76' '65' '69' '60' '80' '54'
 '208' '155' '112' '92' '145' '137' '158' '167' '94' '107' '230' '49' '75'
 '91' '122' '67' '83' '78' '52' '61' '93' '148' '129' '96' '71' '98' '115'
 '53' '81' '79' '120' '152' '102' '108' '68' '58' '149' '89' '63' '48'
 '66' '139' '103' '125' '133' '138' '135' '142' '77' '62' '132' '84' '64'
 '74' '116' '82']

In [16]:

import pandas as pd
import numpy as np

#df = pd.read_csv('auto-mpg.csv')
df = pd.read_csv(
    'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/mpg.csv'
)

df.columns = ['mpg','cylinders','displacement',
              'horsepower','weight',
              'acceleration','model_year',
              'origin','name']

df['origin'] = df['origin'].replace({
    'usa': 1
})

#print(df.head(3))
#print('\n')


mpg_to_kpl = 1.60934/3.78541

df['kpl']=df['mpg']*mpg_to_kpl
print(df.head(3))

df['kpl']=df['kpl'].round(2)
print(df.head(3))

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0

   model_year origin                       name       kpl
0          70      1  chevrolet chevelle malibu  7.652571
1          70      1          buick skylark 320  6.377143
2          70      1         plymouth satellite  7.652571
    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0
1  15.0          8         350.0       165.0    3693          11.5
2  18.0          8         318.0       150.0    3436          11.0

   model_year origin                       name   kpl
0          70      1  chevrolet chevelle malibu  7.65
1          70      1          buick skylark 320  6.38
2          70      1         plymouth satellite  7.65

In [17]:
print(df.dtypes)
print('\n')
print(df['horsepower'].unique())
print('\n')

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
name             object
kpl             float64
dtype: object


[130. 165. 150. 140. 198. 220. 215. 225. 190. 170. 160.  95.  97.  85.
  88.  46.  87.  90. 113. 200. 210. 193.  nan 100. 105. 175. 153. 180.
 110.  72.  86.  70.  76.  65.  69.  60.  80.  54. 208. 155. 112.  92.
 145. 137. 158. 167.  94. 107. 230.  49.  75.  91. 122.  67.  83.  78.
  52.  61.  93. 148. 129.  96.  71.  98. 115.  53.  81.  79. 120. 152.
 102. 108.  68.  58. 149.  89.  63.  48.  66. 139. 103. 125. 133. 138.
 135. 142.  77.  62. 132.  84.  64.  74. 116.  82.]

In [18]:
print(df['origin'].unique())

[1 'japan' 'europe']

In [19]:
df['origin'] = df['origin'].replace({
    'usa': 1,
    'japan': 2,
    'europe': 3
})

C:\Users\student\AppData\Local\Temp\ipykernel_10848\633805448.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['origin'] = df['origin'].replace({

In [20]:
print(df.dtypes)

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin            int64
name             object
kpl             float64
dtype: object

In [21]:
print(df['origin'].unique())

[1 2 3]

In [22]:
 df['origin'].replace({
    1:'usa',
    2:'japan',
    3:'europe'
},inplace=True)

C:\Users\student\AppData\Local\Temp\ipykernel_10848\3862391771.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['origin'].replace({

In [23]:
print(df['origin'].unique())

['usa' 'japan' 'europe']

In [24]:
print(df['origin'].dtypes)

object

In [25]:
df['origin']=df['origin'].astype('category')
print(df['origin'].dtypes)
df['origin']=df['origin'].astype('str')
print(df['origin'].dtypes)

category
object

In [27]:
print(df['model_year'].sample(3))

199    76
13     70
321    80
Name: model_year, dtype: int64

In [28]:
df['model_year']=df['model_year'].astype('category')
print(df['model_year'].sample(3))

303    79
139    74
357    81
Name: model_year, dtype: category
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]

In [29]:
df['horsepower'].replace('?', np.nan, inplace=True)

C:\Users\student\AppData\Local\Temp\ipykernel_10848\2053879960.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].replace('?', np.nan, inplace=True)

In [31]:
df.dropna(subset=['horsepower'], axis=0, inplace=True)
df['horsepower'] = df['horsepower'].astype('float')
count, bin_dividers = np.histogram(df['horsepower'], bins=3)
print(bin_dividers)

[ 46.         107.33333333 168.66666667 230.        ]

In [32]:
bin_names = ['Low output', 'Normal output', 'High output']
df['hp_bin'] = pd.cut(x=df['horsepower'],
                      bins=bin_dividers,
                      labels=bin_names,
                      include_lowest=True)
print(df[['horsepower', 'hp_bin']].head(15))

    horsepower         hp_bin
0        130.0  Normal output
1        165.0  Normal output
2        150.0  Normal output
3        150.0  Normal output
4        140.0  Normal output
5        198.0    High output
6        220.0    High output
7        215.0    High output
8        225.0    High output
9        190.0    High output
10       170.0    High output
11       160.0  Normal output
12       150.0  Normal output
13       225.0    High output
14        95.0     Low output

In [33]:
# Create bins for horsepower
df['hp_bin'] = pd.cut(x=df['horsepower'],
                      bins=bin_dividers,
                      labels=bin_names,
                      include_lowest=True)

# Convert categorical bins into dummy variables
horsepower_dummies = pd.get_dummies(df['hp_bin']).astype('int')

# Display first 15 rows
print(horsepower_dummies.head(15))

    Low output  Normal output  High output
0            0              1            0
1            0              1            0
2            0              1            0
3            0              1            0
4            0              1            0
5            0              0            1
6            0              0            1
7            0              0            1
8            0              0            1
9            0              0            1
10           0              0            1
11           0              1            0
12           0              1            0
13           0              0            1
14           1              0            0

In [34]:
print(df.horsepower.describe())
print('\n')

count    392.000000
mean     104.469388
std       38.491160
min       46.000000
25%       75.000000
50%       93.500000
75%      126.000000
max      230.000000
Name: horsepower, dtype: float64

In [35]:
df.horsepower = df.horsepower / abs(df.horsepower.max())

In [36]:
normalized_value = value / maximum_value

NameError: name 'value' is not defined

In [37]:
print(df.horsepower.head())
print('\n')

0    0.565217
1    0.717391
2    0.652174
3    0.652174
4    0.608696
Name: horsepower, dtype: float64

In [38]:
print(df.horsepower.describe())

count    392.000000
mean       0.454215
std        0.167353
min        0.200000
25%        0.326087
50%        0.406522
75%        0.547826
max        1.000000
Name: horsepower, dtype: float64

In [39]:
print(df.horsepower.describe())
print('\n')

count    392.000000
mean       0.454215
std        0.167353
min        0.200000
25%        0.326087
50%        0.406522
75%        0.547826
max        1.000000
Name: horsepower, dtype: float64

In [ ]:
import pandas as pd
import numpy as np

# Read dataset
df = pd.read_csv('./auto-mpg.csv', header=None)

# Assign column names
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower',
              'weight', 'acceleration', 'model year',
              'origin', 'name']

# Replace missing values
df['horsepower'].replace('?', np.nan, inplace=True)

# Remove missing rows
df.dropna(subset=['horsepower'], axis=0, inplace=True)

# Convert datatype
df['horsepower'] = df['horsepower'].astype('float')

# -------------------------------
# Histogram and Bin Division
# -------------------------------

count, bin_dividers = np.histogram(df['horsepower'], bins=3)

print(bin_dividers)

# -------------------------------
# Create Categories using pd.cut()
# -------------------------------

bin_names = ['Low output', 'Normal output', 'High output']

df['hp_bin'] = pd.cut(x=df['horsepower'],
                      bins=bin_dividers,
                      labels=bin_names,
                      include_lowest=True)

print(df[['horsepower', 'hp_bin']].head(15))

# -------------------------------
# One-Hot Encoding / Dummy Variables
# -------------------------------

horsepower_dummies = pd.get_dummies(df['hp_bin']).astype('int')

print(horsepower_dummies.head(15))

# -------------------------------
# Normalization using Maximum Value
# -------------------------------

print(df.horsepower.describe())
print('\n')

df.horsepower = df.horsepower / abs(df.horsepower.max())

print(df.horsepower.head())
print('\n')

print(df.horsepower.describe())

# -------------------------------
# Min-Max Normalization
# -------------------------------

print(df.horsepower.describe())
print('\n')

min_x = df.horsepower - df.horsepower.min()

min_max = df.horsepower.max() - df.horsepower.min()

df.horsepower = min_x / min_max

print(df.horsepower.head())
print('\n')

print(df.horsepower.describe())