In [1]:
import numpy as np 
import pandas as pd

In [2]:
my_header=['a','b','c']
my_index_out=['G1']*3+['G2']*3
my_index_in=[1,2,3]*2
my_index_zipped=list(zip(my_index_out,my_index_in))
my_index=pd.MultiIndex.from_tuples(my_index_zipped)
df=pd.DataFrame(data=np.random.randn(6,3),index=my_index,columns=my_header)
df

             a         b         c
G1 1  0.381497 -1.475298 -0.720656
   2 -0.380139 -1.417040 -0.289504
   3 -0.189191 -1.023737  0.114860
G2 1 -0.918565  0.670564 -0.229482
   2 -0.232217  0.980432 -0.287342
   3  1.366537  0.495168  0.767278

In [3]:
import pandas as pd

df = pd.read_excel('data_studentlist.xlsx')
df.head()

              Name Gender  Age  Grade Absence Bloodtype  Height  Weight
0    Jared Diamond      M   23      3       Y         O   165.3    68.2
1   Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2     Brian Martin      M   24      4       N         B   175.0    80.1
3     David Hassel      M   23      3       N        AB   182.1    85.7
4  Clara Rodriguez      F   20      1       Y         A   168.0    49.5

In [4]:
df.groupby(['Gender','Bloodtype'])['Height'].mean()

Gender  Bloodtype
F       A            172.450000
        AB           170.100000
        B            158.200000
        O            164.433333
M       A            165.700000
        AB           181.050000
        B            174.550000
        O            166.200000
Name: Height, dtype: float64

In [7]:
my_dict={"Size":["L","L","M","M","M","S","S","S","S"],
         "Type":["A","A","A","B","B","A","A","B","B"],
         "Location":["L1","L1","L1","L2","L2","L1","L2","L2","L1"],
         "A":[1,2,2,3,3,4,5,6,7],
         "B":[2,4,5,5,6,6,8,9,9]}
df=pd.DataFrame(my_dict)
df

  Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9

In [9]:
dfr=pd.pivot_table(df,index=['Size','Type'],columns='Location',values='B')
dfr

Location    L1   L2
Size Type
L    A     3.0  NaN
M    A     5.0  NaN
     B     NaN  5.5
S    A     6.0  8.0
     B     9.0  9.0

In [10]:
dfr.columns

Index(['L1', 'L2'], dtype='object', name='Location')

In [11]:
dfr.index #combination of indexes

MultiIndex([('L', 'A'),
            ('M', 'A'),
            ('M', 'B'),
            ('S', 'A'),
            ('S', 'B')],
           names=['Size', 'Type'])

In [15]:
pd.pivot_table(df,index=['Size','Type'],columns='Location',values='B',fill_value=0)

Location    L1   L2
Size Type
L    A     3.0  0.0
M    A     5.0  0.0
     B     0.0  5.5
S    A     6.0  8.0
     B     9.0  9.0

In [16]:
pd.pivot_table(df,index=['Size','Type'],columns='Location',values='B',aggfunc=np.mean,fill_value=0)

C:\Users\Hp\AppData\Local\Temp\ipykernel_18660\1114501710.py:1: FutureWarning: The provided callable <function mean at 0x00000207C85A5D00> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df,index=['Size','Type'],columns='Location',values='B',aggfunc=np.mean,fill_value=0)

Location    L1   L2
Size Type
L    A     3.0  0.0
M    A     5.0  0.0
     B     0.0  5.5
S    A     6.0  8.0
     B     9.0  9.0

In [17]:
pd.pivot_table(df,index='Location',columns=['Size','Type'],values='B',fill_value=0)

Size        L    M         S
Type        A    A    B    A    B
Location
L1        3.0  5.0  0.0  6.0  9.0
L2        0.0  0.0  5.5  8.0  9.0

In [21]:
pd.pivot_table(df,index=['Size','Type'],values=['A','B'],aggfunc=np.mean)

C:\Users\Hp\AppData\Local\Temp\ipykernel_18660\1001247649.py:1: FutureWarning: The provided callable <function mean at 0x00000207C85A5D00> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df,index=['Size','Type'],values=['A','B'],aggfunc=np.mean)

             A    B
Size Type
L    A     1.5  3.0
M    A     2.0  5.0
     B     3.0  5.5
S    A     4.5  7.0
     B     6.5  9.0

In [22]:
df.groupby(['Size','Type'])[['A','B']].mean()

             A    B
Size Type
L    A     1.5  3.0
M    A     2.0  5.0
     B     3.0  5.5
S    A     4.5  7.0
     B     6.5  9.0

In [24]:
pd.pivot_table(df,index=['Size','Type'],values=['A','B'],aggfunc={'A':np.max,'B':np.min})

C:\Users\Hp\AppData\Local\Temp\ipykernel_18660\131541431.py:1: FutureWarning: The provided callable <function max at 0x00000207C85A5300> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  pd.pivot_table(df,index=['Size','Type'],values=['A','B'],aggfunc={'A':np.max,'B':np.min})
C:\Users\Hp\AppData\Local\Temp\ipykernel_18660\131541431.py:1: FutureWarning: The provided callable <function min at 0x00000207C85A5440> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  pd.pivot_table(df,index=['Size','Type'],values=['A','B'],aggfunc={'A':np.max,'B':np.min})

           A  B
Size Type
L    A     2  2
M    A     2  5
     B     3  5
S    A     5  6
     B     7  9

In [25]:
df.sum(axis=0)

Size                 LLMMMSSSS
Type                 AAABBAABB
Location    L1L1L1L2L2L1L2L2L1
A                           33
B                           54
dtype: object

In [29]:
#df.sum(axis=1) coudnt work because of L M S

In [28]:
#df.mean(axis=0,skipna=False) coudnt work as string not converted to numeric
df.describe()

              A         B
count  9.000000  9.000000
mean   3.666667  6.000000
std    2.000000  2.345208
min    1.000000  2.000000
25%    2.000000  5.000000
50%    3.000000  6.000000
75%    5.000000  8.000000
max    7.000000  9.000000

In [30]:
df.count(axis=0)

Size        9
Type        9
Location    9
A           9
B           9
dtype: int64

In [31]:
df.A.corr(df.B)

np.float64(0.9594032236002469)

In [33]:
 #df.corr()

In [35]:
#df.corrwith(df.A)

In [36]:
df.isnull()

    Size   Type  Location      A      B
0  False  False     False  False  False
1  False  False     False  False  False
2  False  False     False  False  False
3  False  False     False  False  False
4  False  False     False  False  False
5  False  False     False  False  False
6  False  False     False  False  False
7  False  False     False  False  False
8  False  False     False  False  False

In [37]:
(df.isnull()).sum(axis=-0)

Size        0
Type        0
Location    0
A           0
B           0
dtype: int64

In [38]:
(df.isnull()).mean(axis=-0)

Size        0.0
Type        0.0
Location    0.0
A           0.0
B           0.0
dtype: float64

In [39]:
df.dropna(axis=0)  #drop coloumn if it has missing value

  Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9

In [40]:
df.dropna(axis=1)

  Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9

In [41]:
df.dropna(axis=0,thresh=3) #remove rows havinf less than 3 non zero value

  Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9

In [43]:
df.fillna(value=0)

  Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9

In [44]:
#Assignment

In [46]:
'''df.shape
df.size
df.ndim
df.columns
df.index
type(df)
df.info()
df.describe()
df.head(3)
df.tail(3)
df.name'''

'df.shape\ndf.size\ndf.ndim\ndf.columns\ndf.index\ntype(df)\ndf.info()\ndf.describe()\ndf.head(3)\ndf.tail(3)\ndf.name'

In [ ]:
df[['NAME']]
df.loc[:,'NAME']
df.loc[;,['NAME','GENDER']]