In [2]:
data={'math':[90,80,70],'eng':[98,89,95],'music':[85,95,100],'science':[100,90,90]}
data

{'math': [90, 80, 70],
 'eng': [98, 89, 95],
 'music': [85, 95, 100],
 'science': [100, 90, 90]}

In [6]:
import pandas as pd
df=pd.DataFrame(data,index=['stud1','stud2','stud3'])
df

       math  eng  music  science
stud1    90   98     85      100
stud2    80   89     95       90
stud3    70   95    100       90

In [8]:
label1=df.loc['stud1']
print(label1)
position1=df.iloc[0]
print(position1)

math        90
eng         98
music       85
science    100
Name: stud1, dtype: int64
math        90
eng         98
music       85
science    100
Name: stud1, dtype: int64

In [9]:
label2=df.loc[['stud1','stud2']]
print(label2)

       math  eng  music  science
stud1    90   98     85      100
stud2    80   89     95       90

In [10]:
position2=df.iloc[[0,1]]
print(position2)

       math  eng  music  science
stud1    90   98     85      100
stud2    80   89     95       90

In [11]:
math1=df['math']
math1

stud1    90
stud2    80
stud3    70
Name: math, dtype: int64

In [12]:
eng=df.eng
print(eng)

stud1    98
stud2    89
stud3    95
Name: eng, dtype: int64

In [13]:
music_sci=df[['music','science']]
music_sci

       music  science
stud1     85      100
stud2     95       90
stud3    100       90

In [15]:
#df['math']
#2d form
df[['math']]  #matrix form

       math
stud1    90
stud2    80
stud3    70

In [27]:
exam_data={'name':['abc','xyz','pqr'],'math':[90,80,70],'eng':[98,89,95],'music':[85,95,100],'phys_tra':[100,90,90]}
#converting into data frame
df1=pd.DataFrame(exam_data)
print(df1)
df1.index

  name  math  eng  music  phys_tra
0  abc    90   98     85       100
1  xyz    80   89     95        90
2  pqr    70   95    100        90

RangeIndex(start=0, stop=3, step=1)

In [28]:
#convert the name column as the index
df1.set_index('name',inplace=True)
df1.index

Index(['abc', 'xyz', 'pqr'], dtype='object', name='name')

In [29]:
print(df1)

      math  eng  music  phys_tra
name
abc     90   98     85       100
xyz     80   89     95        90
pqr     70   95    100        90

In [31]:
a=df1.loc['abc','music']
a

85

In [32]:
b=df1.loc['abc',['math','phys_tra']]
b

math         90
phys_tra    100
Name: abc, dtype: int64

In [33]:
c=df1.iloc[0,[2,3]]
c

music        85
phys_tra    100
Name: abc, dtype: int64

In [34]:
d=df1.loc['abc','music':'phys_tra']
d

music        85
phys_tra    100
Name: abc, dtype: int64

In [35]:
e=df1.iloc[0,2:]
e

music        85
phys_tra    100
Name: abc, dtype: int64

In [36]:
f=df1.loc[['abc','xyz'],['music','phys_tra']]
f

      music  phys_tra
name
abc      85       100
xyz      95        90

In [37]:
g=df.iloc[[0,1],[2,3]]
g

       music  science
stud1     85      100
stud2     95       90

In [40]:
h=df1.loc['abc':'xyz','music':'phys_tra']
h

      music  phys_tra
name
abc      85       100
xyz      95        90

In [41]:
#add a column
df1['kor']=80
df1

      math  eng  music  phys_tra  kor
name
abc     90   98     85       100   80
xyz     80   89     95        90   80
pqr     70   95    100        90   80

In [43]:
#add a row
df1.loc[4]=0
df1.loc['mnp']=0
df1

      math  eng  music  phys_tra  kor
name
abc     90   98     85       100   80
xyz     80   89     95        90   80
pqr     70   95    100        90   80
4        0    0      0         0    0
mnp      0    0      0         0    0

In [44]:
df1.drop(4,axis=0,inplace=True)
df1

      math  eng  music  phys_tra  kor
name
abc     90   98     85       100   80
xyz     80   89     95        90   80
pqr     70   95    100        90   80
mnp      0    0      0         0    0

In [45]:
df1.loc['mnp']=[90,80,70,60,77]
df1

      math  eng  music  phys_tra  kor
name
abc     90   98     85       100   80
xyz     80   89     95        90   80
pqr     70   95    100        90   80
mnp     90   80     70        60   77

In [46]:
print(df1.index)

Index(['abc', 'xyz', 'pqr', 'mnp'], dtype='object', name='name')

In [49]:
print(df1.index[3])

mnp

In [51]:
#name is not the index anymore
df1=df1.reset_index()
df1

  name  math  eng  music  phys_tra  kor
0  abc    90   98     85       100   80
1  xyz    80   89     95        90   80
2  pqr    70   95    100        90   80
3  mnp    90   80     70        60   77

In [52]:
df1.iloc[3,0]='lmn'
df1

  name  math  eng  music  phys_tra  kor
0  abc    90   98     85       100   80
1  xyz    80   89     95        90   80
2  pqr    70   95    100        90   80
3  lmn    90   80     70        60   77

In [53]:
df1.set_index('name',inplace=True)
df1

      math  eng  music  phys_tra  kor
name
abc     90   98     85       100   80
xyz     80   89     95        90   80
pqr     70   95    100        90   80
lmn     90   80     70        60   77

In [54]:
df1.iloc[3][0]=100
df1

C:\Users\student\AppData\Local\Temp\ipykernel_18128\2158646870.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1.iloc[3][0]=100
C:\Users\student\AppData\Local\Temp\ipykernel_18128\2158646870.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  df1.iloc[3][0]=100

      math  eng  music  phys_tra  kor
name
abc     90   98     85       100   80
xyz     80   89     95        90   80
pqr     70   95    100        90   80
lmn    100   80     70        60   77

In [55]:
df1.iloc[3,0]=99
df1

      math  eng  music  phys_tra  kor
name
abc     90   98     85       100   80
xyz     80   89     95        90   80
pqr     70   95    100        90   80
lmn     99   80     70        60   77

In [57]:
#df1.loc['abc','math']=100
#df1
df1.loc['abc']['math']=90
df1

C:\Users\student\AppData\Local\Temp\ipykernel_18128\1697061540.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1.loc['abc']['math']=90

      math  eng  music  phys_tra  kor
name
abc     90   98     85       100   80
xyz     80   89     95        90   80
pqr     70   95    100        90   80
lmn     99   80     70        60   77

In [58]:
df1.loc['abc',['math','eng']]=50
df1

      math  eng  music  phys_tra  kor
name
abc     50   50     85       100   80
xyz     80   89     95        90   80
pqr     70   95    100        90   80
lmn     99   80     70        60   77

In [59]:
df1.loc['abc',['math','eng']]=50,40
df1

      math  eng  music  phys_tra  kor
name
abc     50   40     85       100   80
xyz     80   89     95        90   80
pqr     70   95    100        90   80
lmn     99   80     70        60   77

In [61]:
df1.reset_index(inplace=True)
df1

  name  math  eng  music  phys_tra  kor
0  abc    50   40     85       100   80
1  xyz    80   89     95        90   80
2  pqr    70   95    100        90   80
3  lmn    99   80     70        60   77

In [63]:
dff=df1.transpose()
print(dff)
dfff=dff.T
print(dfff)

            0    1    2    3
name      abc  xyz  pqr  lmn
math       50   80   70   99
eng        40   89   95   80
music      85   95  100   70
phys_tra  100   90   90   60
kor        80   80   80   77
  name math eng music phys_tra kor
0  abc   50  40    85      100  80
1  xyz   80  89    95       90  80
2  pqr   70  95   100       90  80
3  lmn   99  80    70       60  77

In [64]:
df1.set_index('name',inplace=True)
df1

      math  eng  music  phys_tra  kor
name
abc     50   40     85       100   80
xyz     80   89     95        90   80
pqr     70   95    100        90   80
lmn     99   80     70        60   77

In [65]:
df1.reset_index(inplace=True)
df1

  name  math  eng  music  phys_tra  kor
0  abc    50   40     85       100   80
1  xyz    80   89     95        90   80
2  pqr    70   95    100        90   80
3  lmn    99   80     70        60   77

In [67]:
ndf=df1.set_index(['name'])
ndf

      math  eng  music  phys_tra  kor
name
abc     50   40     85       100   80
xyz     80   89     95        90   80
pqr     70   95    100        90   80
lmn     99   80     70        60   77

In [68]:
ndf1=ndf.set_index('math')
ndf1
#ndf1 = ndf.reset_index().set_index('math')   if u want to keep the name

      eng  music  phys_tra  kor
math
50     40     85       100   80
80     89     95        90   80
70     95    100        90   80
99     80     70        60   77

In [69]:
ndf2=ndf.set_index(['math','music'])
ndf2

            eng  phys_tra  kor
math music
50   85      40       100   80
80   95      89        90   80
70   100     95        90   80
99   70      80        60   77

In [70]:
dict_data={'c0':[1,2,3],'c1':[4,5,6],'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,15]}
df=pd.DataFrame(dict_data,index=['r0','r1','r2'])
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [72]:
new_index=['r1','r2','r3','r4']
ndf=df.reindex(new_index)
ndf

     c0   c1   c2    c3    c4
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN

In [74]:
new_index=['r1','r2','r3','r4']
ndf1=df.reindex(new_index,fill_value=0)
ndf1

    c0  c1  c2  c3  c4
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

In [75]:
ndf1.reset_index()
ndf1

    c0  c1  c2  c3  c4
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0