In [1]:
import pandas as pd 
pd.Series(['male','female','male','male','female','female','female'])

0      male
1    female
2      male
3      male
4    female
5    female
6    female
dtype: object

In [5]:
data={'a':1,'b':2,'c':3}  #seies with dictionary
s1=pd.Series(data)
print(s1)
print(type(s1))
print(s1.index)
print(s1.values)

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>
Index(['a', 'b', 'c'], dtype='object')
[1 2 3]

In [10]:
df=pd.DataFrame({"name":["hija,hippo","allen,ajjo","bonni,bonel"],"age":[22,35,46],"sex":["male","female","male"]})
print(df['age'])
type(df['age'])
print(df['age'][0])

0    22
1    35
2    46
Name: age, dtype: int64
22

In [17]:
df1=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
print(df1.columns)
print(df1[1])

RangeIndex(start=0, stop=3, step=1)
0    2
1    5
2    8
Name: 1, dtype: int64

In [23]:
eye=pd.Series({'brown':220,'blue':215,'hazel':93,'green':64})
eye.index
type(eye)
eye.name="eye_color"
print(eye)

brown    220
blue     215
hazel     93
green     64
Name: eye_color, dtype: int64

In [32]:
iris_df=pd.read_csv("iris.data.csv")
print(iris_df)

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [28]:
import os
print(os.getcwd())

C:\Users\Student

In [31]:
type(iris_df)

pandas.core.frame.DataFrame

In [33]:
iris_df.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [34]:
iris_df.tail()

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [35]:
iris_df.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [36]:
iris_df.index

RangeIndex(start=0, stop=149, step=1)

In [37]:
iris_df.columns=['sepal_length','spal_width','petal_length','petal_width','species']
print(iris_df)

     sepal_length  spal_width  petal_length  petal_width         species
0             4.9         3.0           1.4          0.2     Iris-setosa
1             4.7         3.2           1.3          0.2     Iris-setosa
2             4.6         3.1           1.5          0.2     Iris-setosa
3             5.0         3.6           1.4          0.2     Iris-setosa
4             5.4         3.9           1.7          0.4     Iris-setosa
..            ...         ...           ...          ...             ...
144           6.7         3.0           5.2          2.3  Iris-virginica
145           6.3         2.5           5.0          1.9  Iris-virginica
146           6.5         3.0           5.2          2.0  Iris-virginica
147           6.2         3.4           5.4          2.3  Iris-virginica
148           5.9         3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

In [44]:
#iris_df.sepal_length   #df['sepal_length']
print(iris_df[['sepal_length','spal_width']])

     sepal_length  spal_width
0             4.9         3.0
1             4.7         3.2
2             4.6         3.1
3             5.0         3.6
4             5.4         3.9
..            ...         ...
144           6.7         3.0
145           6.3         2.5
146           6.5         3.0
147           6.2         3.4
148           5.9         3.0

[149 rows x 2 columns]

In [45]:
df=pd.DataFrame([['Tom',15,'Male','middle'],['Alice',10,'Female','elementary']],columns=['Name','Age','Sex','School'])
df

    Name  Age     Sex      School
0    Tom   15    Male      middle
1  Alice   10  Female  elementary

In [46]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [48]:
#naming index
df.index=['stud1','stud2']
df.index

Index(['stud1', 'stud2'], dtype='object')

In [51]:
df=df.rename(index={'stud1':'student1'})
df

           Name  Age     Sex      School
student1    Tom   15    Male      middle
stud2     Alice   10  Female  elementary

In [55]:
#another waay
df.rename(index={'stud2':'student2'},inplace=True)
df

AttributeError: 'NoneType' object has no attribute 'rename'

In [56]:
print(type(df))

<class 'NoneType'>

In [58]:
df = pd.read_csv("iris.data.csv")

df.rename(index={'stud2': 'student2'}, inplace=True)
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [60]:
df1=pd.DataFrame([['Tom',15,'Male','middle'],['Alice',10,'Female','elementary']],columns=['Name','Age','Sex','School'])
df1

    Name  Age     Sex      School
0    Tom   15    Male      middle
1  Alice   10  Female  elementary

In [61]:
df1.index

RangeIndex(start=0, stop=2, step=1)

In [62]:
#naming index
df1.index=['stud1','stud2']
df1.index

Index(['stud1', 'stud2'], dtype='object')

In [63]:
df1=df1.rename(index={'stud1':'student1'})
df1

           Name  Age     Sex      School
student1    Tom   15    Male      middle
stud2     Alice   10  Female  elementary

In [64]:
#another waay
df1.rename(index={'stud2':'student2'},inplace=True)
df1

           Name  Age     Sex      School
student1    Tom   15    Male      middle
student2  Alice   10  Female  elementary

In [ ]:
#rename column in the same way
#with using inplace

In [65]:
exam_data={'math':[90,80,70],'eng':[98,89,95],'music':[85,95,100],'science':[100,90,90]}
exam_data

{'math': [90, 80, 70],
 'eng': [98, 89, 95],
 'music': [85, 95, 100],
 'science': [100, 90, 90]}

In [67]:
df2=pd.DataFrame(exam_data,index=['stud1','stud2','stud3'])
df2

       math  eng  music  science
stud1    90   98     85      100
stud2    80   89     95       90
stud3    70   95    100       90

In [68]:
df_copy=df2[:]
df_copy.drop('stud2',inplace=True)
df_copy

C:\Users\Student\AppData\Local\Temp\ipykernel_14128\2990276337.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_copy.drop('stud2',inplace=True)

       math  eng  music  science
stud1    90   98     85      100
stud3    70   95    100       90

In [69]:
df2

       math  eng  music  science
stud1    90   98     85      100
stud2    80   89     95       90
stud3    70   95    100       90

In [71]:
#multiple rows
df3=df2[:]
df3.drop(['stud2','stud3'],axis=0,inplace=True)
df3

C:\Users\Student\AppData\Local\Temp\ipykernel_14128\2783543889.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop(['stud2','stud3'],axis=0,inplace=True)

       math  eng  music  science
stud1    90   98     85      100